-- Core schema for the Movie Ticket Booking system.
-- Feature tables (payment, pricing_tier, discount_code, refund_policy, notification)
-- are added in later migrations, alongside the milestone that introduces them.

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL          -- ADMIN | CUSTOMER
);

CREATE TABLE city (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL
);

CREATE TABLE theater (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL REFERENCES city(id),
    name    VARCHAR(150) NOT NULL
);

CREATE TABLE screen (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theater_id BIGINT NOT NULL REFERENCES theater(id),
    name       VARCHAR(100) NOT NULL
);

CREATE TABLE seat (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id   BIGINT NOT NULL REFERENCES screen(id),
    row_label   VARCHAR(5)  NOT NULL,
    seat_number INT         NOT NULL,
    tier        VARCHAR(20) NOT NULL,           -- REGULAR | PREMIUM
    UNIQUE (screen_id, row_label, seat_number)
);

CREATE TABLE movie (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200) NOT NULL,
    duration_min INT          NOT NULL
);

CREATE TABLE shows (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id  BIGINT       NOT NULL REFERENCES screen(id),
    movie_id   BIGINT       NOT NULL REFERENCES movie(id),
    start_time TIMESTAMPTZ  NOT NULL,
    base_price NUMERIC(10,2) NOT NULL
);

CREATE TABLE seat_hold (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id    BIGINT      NOT NULL REFERENCES shows(id),
    user_id    BIGINT      NOT NULL REFERENCES app_user(id),
    status     VARCHAR(20) NOT NULL,            -- ACTIVE | EXPIRED | CONVERTED
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE booking (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES app_user(id),
    show_id         BIGINT       NOT NULL REFERENCES shows(id),
    status          VARCHAR(20)  NOT NULL,      -- CONFIRMED | CANCELLED
    total_amount    NUMERIC(10,2) NOT NULL,
    idempotency_key VARCHAR(100) UNIQUE,        -- dedups retried submits
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- The bookable unit: one physical seat for one show. This is the row we lock.
CREATE TABLE show_seat (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id    BIGINT       NOT NULL REFERENCES shows(id),
    seat_id    BIGINT       NOT NULL REFERENCES seat(id),
    status     VARCHAR(20)  NOT NULL,           -- AVAILABLE | HELD | BOOKED
    price      NUMERIC(10,2) NOT NULL,
    version    BIGINT       NOT NULL DEFAULT 0, -- optimistic-lock guard (JPA @Version)
    hold_id    BIGINT       REFERENCES seat_hold(id),
    held_until TIMESTAMPTZ,
    booking_id BIGINT       REFERENCES booking(id),
    UNIQUE (show_id, seat_id)
);

CREATE INDEX idx_theater_city       ON theater(city_id);
CREATE INDEX idx_shows_screen       ON shows(screen_id);
CREATE INDEX idx_show_seat_show     ON show_seat(show_id, status);
CREATE INDEX idx_show_seat_expiry   ON show_seat(held_until) WHERE status = 'HELD';
