-- Payment captured at booking time (mock gateway; always succeeds in this build).
CREATE TABLE payment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id   BIGINT       NOT NULL REFERENCES booking(id),
    amount       NUMERIC(10,2) NOT NULL,
    status       VARCHAR(20)  NOT NULL,          -- SUCCESS | FAILED
    provider_ref VARCHAR(100),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_payment_booking ON payment(booking_id);
