CREATE TABLE discount_code (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   VARCHAR(50)  NOT NULL UNIQUE,
    type   VARCHAR(20)  NOT NULL,          -- PERCENTAGE | FLAT
    value  NUMERIC(10,2) NOT NULL,
    active BOOLEAN      NOT NULL DEFAULT true
);

INSERT INTO discount_code (code, type, value, active) VALUES
  ('SAVE10',  'PERCENTAGE', 10.00, true),   -- 10% off
  ('FLAT50',  'FLAT',       50.00, true),   -- flat 50 off
  ('EXPIRED', 'PERCENTAGE', 20.00, false);  -- inactive, for negative testing

-- Record which code (if any) was applied to a booking.
ALTER TABLE booking ADD COLUMN discount_code VARCHAR(50);
