CREATE TABLE notification (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    booking_id BIGINT      NOT NULL REFERENCES booking(id) ON DELETE CASCADE,
    channel    VARCHAR(20) NOT NULL,          -- EMAIL | SMS | PUSH | IN_APP
    message    TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_notification_booking ON notification(booking_id);
