-- Enriches the catalog so browse/search and the demo are realistic: more cities,
-- theaters, screens, seats, movies, shows (incl. weekend-priced and every refund tier),
-- users, and discount codes. ADD-ONLY: the V2 seed (show 1, seats 1-10, Bengaluru,
-- Inception, admin/alice/bob, SAVE10/FLAT50/EXPIRED) is left untouched.
--
-- Two test-safety rules honored deliberately:
--   1. No new show lives in a city named 'Bengaluru' -> the GET /shows?city=bengaluru
--      "exactly one" filter test stays valid (it proves the filter actually filters).
--   2. Near-term shows are added (for the refund demo) and the browse test was made
--      position-independent (hasItem), so first-element ordering is no longer assumed.
--
-- IDs: every table is GENERATED BY DEFAULT AS IDENTITY. We omit ids everywhere and use
-- RETURNING ... INTO (so the identity sequence always advances -> no runtime PK clashes).
--
-- Pricing model (matches show 1): show_seat.price = base_price for REGULAR, base_price+100
-- for PREMIUM. The weekend x1.25 surcharge is applied at BOOKING time from the seat's
-- UTC day-of-week, so we do NOT pre-multiply here.

DO $$
DECLARE
    city_mumbai  BIGINT;
    city_delhi   BIGINT;
    city_hyd     BIGINT;
    th_mumbai    BIGINT;
    th_delhi     BIGINT;
    th_hyd       BIGINT;
    sc_imax      BIGINT;
    sc_mumbai2   BIGINT;
    sc_delhi1    BIGINT;
    sc_hyd1      BIGINT;
    mv_dune      BIGINT;
    mv_oppen     BIGINT;
    mv_inter     BIGINT;
    mv_batman    BIGINT;
    -- "Weekend" is decided in UTC (ZoneOffset.UTC) by the pricing strategy, so build the
    -- slots from the UTC week start to guarantee the UTC day-of-week, regardless of when
    -- the grader runs. date_trunc('week', ...) = Monday 00:00; +12d = Sat next week,
    -- +8d = Tue next week. Both are comfortably > show 1's start (now()+1 day).
    weekend_slot TIMESTAMPTZ := (date_trunc('week', now() AT TIME ZONE 'UTC') + interval '12 days 18 hours') AT TIME ZONE 'UTC';
    weekday_slot TIMESTAMPTZ := (date_trunc('week', now() AT TIME ZONE 'UTC') + interval '8 days 18 hours')  AT TIME ZONE 'UTC';
BEGIN
    -- Cities (none named 'Bengaluru')
    INSERT INTO city (name) VALUES ('Mumbai')    RETURNING id INTO city_mumbai;
    INSERT INTO city (name) VALUES ('Delhi')     RETURNING id INTO city_delhi;
    INSERT INTO city (name) VALUES ('Hyderabad') RETURNING id INTO city_hyd;

    -- Theaters
    INSERT INTO theater (city_id, name) VALUES (city_mumbai, 'PVR Phoenix Lower Parel') RETURNING id INTO th_mumbai;
    INSERT INTO theater (city_id, name) VALUES (city_delhi,  'INOX Nehru Place')        RETURNING id INTO th_delhi;
    INSERT INTO theater (city_id, name) VALUES (city_hyd,    'AMB Cinemas Gachibowli')  RETURNING id INTO th_hyd;

    -- Screens
    INSERT INTO screen (theater_id, name) VALUES (th_mumbai, 'IMAX')     RETURNING id INTO sc_imax;
    INSERT INTO screen (theater_id, name) VALUES (th_mumbai, 'Audi 2')   RETURNING id INTO sc_mumbai2;
    INSERT INTO screen (theater_id, name) VALUES (th_delhi,  'Screen 1') RETURNING id INTO sc_delhi1;
    INSERT INTO screen (theater_id, name) VALUES (th_hyd,    'Screen 1') RETURNING id INTO sc_hyd1;

    -- Seat layout per new screen: rows A,B = REGULAR and C,D = PREMIUM, seats 1..6 (24/screen).
    INSERT INTO seat (screen_id, row_label, seat_number, tier)
    SELECT scr.id, r.row_label, seat_number,
           CASE WHEN r.row_label IN ('A', 'B') THEN 'REGULAR' ELSE 'PREMIUM' END
    FROM (VALUES (sc_imax), (sc_mumbai2), (sc_delhi1), (sc_hyd1)) AS scr(id)
    CROSS JOIN (VALUES ('A'), ('B'), ('C'), ('D')) AS r(row_label)
    CROSS JOIN generate_series(1, 6) AS seat_number;

    -- Movies
    INSERT INTO movie (title, duration_min) VALUES ('Dune: Part Two', 166)  RETURNING id INTO mv_dune;
    INSERT INTO movie (title, duration_min) VALUES ('Oppenheimer', 180)     RETURNING id INTO mv_oppen;
    INSERT INTO movie (title, duration_min) VALUES ('Interstellar', 169)    RETURNING id INTO mv_inter;
    INSERT INTO movie (title, duration_min) VALUES ('The Dark Knight', 152) RETURNING id INTO mv_batman;

    -- Shows. base_price drives seat prices (REGULAR=base, PREMIUM=base+100).
    -- Weekend-priced (UTC Saturday): IMAX Dune -> REGULAR 300 / PREMIUM 400, x1.25 at booking.
    INSERT INTO shows (screen_id, movie_id, start_time, base_price) VALUES (sc_imax,    mv_dune,   weekend_slot, 300.00);
    -- Weekday-priced: Oppenheimer -> REGULAR 220 / PREMIUM 320, no surcharge.
    INSERT INTO shows (screen_id, movie_id, start_time, base_price) VALUES (sc_mumbai2, mv_oppen,  weekday_slot, 220.00);
    -- Refund-tier demo shows (tier decided at cancel time vs start_time):
    --   FULL  (>=24h): now()+25h
    INSERT INTO shows (screen_id, movie_id, start_time, base_price) VALUES (sc_delhi1,  mv_inter,  now() + interval '25 hours',   200.00);
    --   HALF  (>=2h,<24h): now()+12h
    INSERT INTO shows (screen_id, movie_id, start_time, base_price) VALUES (sc_delhi1,  mv_batman, now() + interval '12 hours',   200.00);
    --   NONE  (<2h): now()+45min
    INSERT INTO shows (screen_id, movie_id, start_time, base_price) VALUES (sc_hyd1,    mv_dune,   now() + interval '45 minutes', 180.00);
    -- A couple more future shows for browse richness.
    INSERT INTO shows (screen_id, movie_id, start_time, base_price) VALUES (sc_hyd1,    mv_oppen,  now() + interval '3 days',     250.00);
    INSERT INTO shows (screen_id, movie_id, start_time, base_price) VALUES (sc_delhi1,  mv_dune,   now() + interval '4 days',     230.00);
END $$;

-- Materialize show_seats for every show that doesn't have them yet (i.e. the new ones;
-- show 1 already has its 10). Set-based and id-agnostic: each show gets one bookable seat
-- per seat of its screen, priced by tier off the show's base_price.
INSERT INTO show_seat (show_id, seat_id, status, price)
SELECT sh.id, s.id, 'AVAILABLE',
       CASE WHEN s.tier = 'PREMIUM' THEN sh.base_price + 100.00 ELSE sh.base_price END
FROM shows sh
JOIN seat s ON s.screen_id = sh.screen_id
WHERE NOT EXISTS (
    SELECT 1 FROM show_seat ss WHERE ss.show_id = sh.id AND ss.seat_id = s.id
);

-- More customers (password = "password", same bcrypt hash as the seeded users).
INSERT INTO app_user (username, password_hash, role) VALUES
    ('carol', '$2y$10$acjw/qSx7NOaazhDKz6V/.XrnJQQgMHdsNEpclL.bExoCrJ6I.tnS', 'CUSTOMER'),
    ('dave',  '$2y$10$acjw/qSx7NOaazhDKz6V/.XrnJQQgMHdsNEpclL.bExoCrJ6I.tnS', 'CUSTOMER');

-- More discount codes (no date-expiry in the model; validity is the active flag).
INSERT INTO discount_code (code, type, value, active) VALUES
    ('WELCOME25', 'PERCENTAGE',  25.00, true),
    ('FLAT100',   'FLAT',       100.00, true),
    ('STUDENT15', 'PERCENTAGE',  15.00, true);
